CARD_SINGLE = "single"
CARD_MONTHLY = "monthly"
CARD_TYPES = frozenset({CARD_SINGLE, CARD_MONTHLY})

PLATFORM_ALL = "all"
PLATFORM_XXQD = "xxqd"
PLATFORM_CLASS_CUBE = "class_cube"
PLATFORM_SCOPES = frozenset(
    {PLATFORM_ALL, PLATFORM_XXQD, PLATFORM_CLASS_CUBE}
)

MONTHLY_CARD_DAYS = 30

DEFAULT_CARD_DELETE_DELAY_SECONDS = 60
MIN_CARD_DELETE_DELAY_SECONDS = 0
MAX_CARD_DELETE_DELAY_SECONDS = 24 * 60 * 60

DEFAULT_CARD_TOTAL_USES = 1
MIN_CARD_TOTAL_USES = 1
MAX_CARD_TOTAL_USES = 999

DEFAULT_LOCATION_SEARCH_DAILY_LIMIT = 100
